ivfflat-bq-rerank-openai-1536-5m-8k:
  indexType: ivfflat_bq_rerank
  dataset: openai-5m-cos
  datasetType: hdf5
  metric: cos
  lists: 8000 #
  scan_limit: 250
  maintenance_work_mem: 24GB
  pg_parallel_workers: 10
  top: 10
  benchmarks:
    probes250-rerank25:
      probes: 250
      rerank_limit_amplify_factor: 25
    probes280-rerank25:
      probes: 280
      rerank_limit_amplify_factor: 25
    probes100-rerank25:
      probes: 100
      rerank_limit_amplify_factor: 25
