vc-cohere-10m-180-32k:
  dataset: cohere-10m-cos
  datasetType: parquet
  metric: cos
  samplingFactor: 256
  lists: [180, 32768]
  build_threads: 32
  residual_quantization: true
  kmeans_hierarchical: true
  rerank_in_table: true
  pg_parallel_workers: 32
  top: 10
  benchmarks:
    20-40-1.9:
      nprob: 20,40
      epsilon: 1.9
    38-76-1.9:
      nprob: 38,76
      epsilon: 1.9
    50-100-1.9:
      nprob: 50,100
      epsilon: 1.9
    65-130-1.9:
      nprob: 65,130
      epsilon: 1.9
    80-160-1.9:
      nprob: 80,160
      epsilon: 1.9
    100-200-1.9:
      nprob: 100,200
      epsilon: 1.9
